spring:
  application:
    name: orders
  datasource:
    url: jdbc:postgresql://amazondb.crdhamcx3fst.us-east-1.rds.amazonaws.com
    username: amazon
    password: amazon1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql

  rabbitmq:
    host: 91.126.226.193
    port: 27033
    username: admin
    password: admin

external:
  api:
    base:
      url: https://workshop-7uvd.onrender.com/api/v1
