spring:
  application:
    name: orders
  datasource:
    url: jdbc:postgresql://localhost:5432/springdb
    username: springuser
    password: springpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql

external:
  api:
    base:
      url: https:https://workshop-7uvd.onrender.com/api/v1
