spring:
  application:
    name: pedidos

  datasource:
    url: jdbc:postgresql://localhost:5432/springdb
    driver-class-name: org.postgresql.Driver
    user: springuser
    password: springpass

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      schema-locations: classpath:/db/schema.sql
      mode: always